/* eslint-disable no-unused-vars */
module.exports = {
	name: 'rap',
	description: 'Check out some cool raps!',
	execute(msg, args) {
		const client = msg.client;
		const Discord = require('discord.js');
		const mysql = require('mysql');
		const connection = mysql.createConnection({
			host: 'localhost',
			user: 'root',
			password: 'latehome4',
			database:'discord',
			charset : 'utf8mb4',
		});
		var number = 0;

		var text = msg.content.slice(5).trim().split(' ');
			if (text == 1){
				msg.channel.send("**Rap #1 - Friend**\n\nYeah, I was walking\nYeah, I was walking\nAll alone, by myself\nCuz I ain\'t got no friends yet\nI just need someone\nThat will stay\nBy my side til the end\nI wish I had a friend\nI wish I had a friend\nI\'m outside at night\nWith Me, Myself and I\nAnd I don\'t know why\nThese people don\'t like me\nDo you think I\'m high?\nTell me the truth don\'t lie\nIs it cuz I can\'t afford a home\nAnd I can\'t afford a bed\nAnd I can\'t afford some food\nAnd I can\'t afford good clothes\nYeah, I can\'t afford nothing\nI can\'t afford nothing\nBut God just give me one thing\n\n- A Friend")
			}
			else if (text == 2){
				msg.channel.send("**Rap #2 - Frappe or Cappe**\n\nAyy, I just f###ed a b##ch,\nI f###ed her in Paris and left her in a ditch\nI left her in a ditch cuz she a f###ing snitch\nFound another girl, and I took her to fry fish\nYo, I\'m a god and you ain\'t, you wish\nI\'m a f###ing god and your f###ing doodoo\nYou a piece of s###, go eat some poopoo\nI was walking, she was talking\nSaw a guy, and we start gawking\nCause he was outside, jaywalking\nHe asked, you got any skills and this was my answer\nYo you know that I\'m an epic dancer\nI was out in London and started moonwalking\nAll the people out there came to me, started flocking\nAnd everyone knows that I\'m the best rapper\nCuz I\'m the commander and you a salamander\nThese kids be tryharding, they\'re noobs for real\nBro you so fat you\'re an elephant seal\nFight me b##ch, I\'ll peel you like a banana\nYou be trying to look cool with Lil Mosey\'s bandana\nRemember in his song he says blueberry faygo\nHe was talking to you, saying f###ot-just go\nOh, you a mother f###ing a## h##\nCome see my concert, I put up a big show\nYo, when the lights turn off I glow\nIts easy for me, I go with the flow\nI took her on a trip with a lotta cargo\nI went hunting, got a lotta ammo\nShe\'s pretty bad, she a oldstyle he\nI got the rifle, and she got the crossbow\nAnd then we went to a b-ball game show\nI took a shot and I made the free throw\nAnd then I left her and went to a plateau\nSaw a rhino, so I took a photo\nThen I walked all the way back to my Lambo\nI went inside and turned on the radio\nAnd guess what, the song was lit\nTurns out that they were playing Juice WRLD\nWhich is a good thing cuz he\'s outta this world\nAnd then I saw this stupid a## kid\nI almost hit him, but I slid\nI asked him if he was hurt\nHe said no, that was a lit skrrt\nAnd now its the end of my epic rap\nBut before I go I got something to ask\nDo you prefer a frappe or a cappe?\nI know what I like- a frappacappe")
			}
			else if (text == 3){
				msg.channel.send("**Rap #3 - What did you do - Parody of Bands out the Roof by Lil Mosey**\n\nOoh, what the f### did you do\nWhat did you do to my expensive shoes\nYou, are f###ing poopoo\nI\'m in L.A. with a bad b##ch too\nOoh, you a bad b##ch too\nWhat should I do, Imma pull up on you\nI\'m on the roof wearing my Gucci shoes\nOoh, you a b##ch f### you\nF### you as I walk through\nYeah you want me but I don\'t want you\nBaby throw it back, I put it on you\nThey just want the racks, they don\'t want you\nPlaques on plaques yeah, that\'s a hundred trophies\nHate what I did to get these diamonds on me\nStill hittin\' licks, got new Amiri on me\nB-Bustdown, yeah, got some racks on my Rollie\nSome things, we\'ll never be\nMoney, cars, b##ches there for me\nSing you a lil\' symphony\nCheated on you, give me sympathy\nOoh, what the f### did you do\nWhat did you do to my expensive shoes\nYou, are f###ing poopoo\nI\'m in L.A. with a bad b##ch too\nOoh, you a bad b##ch too\nWhat should I do, Imma pull up on you\/I\'m on the roof wearing my Gucci shoes\nOoh, you a b##ch f### you\nYeah, yeah, yeah, yeah, yeah\nI am the man, man, man, man\nHopped out on you, they popped out again\nBands, bands, I\'m thumbin\'Just chill and relax, lay in the pool\nThey say you want, still pull up back to\nRarri, I\'m gone, still got the same coupe\nFlowing on songs, still popping things too\nSome things, we\'ll never be\nMoney, cars, b##ches there for me\nSing you a lil\' symphony\nCheated on you, give me sympathy\nOoh, what the f### did you do\nWhat did you do to my expensive shoes\nYou, are f###ing poopoo\nI\'m in L.A. with a bad b##ch too\nOoh, you a bad b##ch too\nWhat should I do, Imma pull up on you\nI\'m on the roof wearing my Gucci shoes\nOoh, you a b##ch f### you\nOoh, yeah Royce got the juice\nHe got the Rolls Royce and he skrrted off too\nOoh, and I\'m lookin\' very cool\nIce on my neck, yeah, you got some too\nYeah, yeah what did you do, lookin\' like a fool\nRuined my gucci shoes\nYeah, big s###")
			}
			else if (text == 4) {
				msg.channel.send("**Rap #4 - Love You**\n\nYeah, I haven\’t told you this\nIt\’s, been a while\nAnd now, I think it\’s time\nTime, to tell you this\n\nGirl, every time I see you\nIt’s like I can\’t move\nI get so confused \nGirl, every time I see you\nIt\’s like I can\’t move\nLove how you stay cool\n\nThat\’s why I love you, love you, love you, love you, love you, love you\nYeah yeah, I love you, love you, love you, love you, love you, love you\nOh yes I love you, love you, love you, love you, love you, love you\nYeah girl I love you, love you, love you, love you, love you, love you (oooh)\n\nGirl, you\’re so beautiful\nYou\’re too pretty, it\’s wonderful\nYou\’re super hot, incredible\nGirl you\’re so cute, so lovable\nI want your love, make my heart full\nI want your heart, make my heart whole (whole, whole, whole)\nYeah make it whole (whole, whole, whole)\nMake my heart whole (whole, whole, whole)\nYeah girl, make my heart whole (whole, whole, whole)\n\nOh yeah, I love you, love you, love you, love you, love you, love you\nYeah yeah, I love you, love you, love you, love you, love you, love you\nOh yes I love you, love you, love you, love you, love you, love you\nYeah girl I love you, love you, love you, love you, love you, love you (oooh)\n\nWherever you go I\’ll follow you\nWherever you go I\’ll come with you\nYeah, I love you all the way\nPlease come back I miss your face\nGirl for you there\’s always space\nCome with me on one last date\nPromise you I won\’t be late\nUs together, it\’s our fate\nGirl can you be my soul mate?\n\nOh yeah, I love you, love you, love you, love you, love you, love you\nYeah yeah, I love you, love you, love you, love you, love you, love you\nOh yes I love you, love you, love you, love you, love you, love you\nYeah girl I love you, love you, love you, love you, love you, love you (oooh)\n\nGirl, don\’t run away\nI, want you to stay\nLet\’s, do this my way\nYeah, you are my babe")
			}
			else if (text == 5) {
				msg.channel.send("**Rap #5 - Viral**\n\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral\nI just went viral, viral\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral \nI just went viral, viral\n(Yeah)\nJust so you know this\nI’m tellin\’ you this\nI go viral faster than the corona virus\nYeah gotta do it\nYeah gotta make it\nGotta get up there, that\’s what I\’m thinkin\’\nYeah I\’m popular\nYeah I\’m famous\nChillz, that\’s what my name is\nWhat do you want?\nJust tell me what you want\nMy fans love me and I love them\n\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral\nI just went viral, viral\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral \nI just went viral, viral\n(Yeah)\n\nI just went viral,\nHaven’t you heard\nFrom here I go up, up, up \nLike a bird\n\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral \nI just went viral, viral\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral \nI just went viral, viral\nViral, viral,\nI just went viral, viral\nYeah I went viral, viral \nI just went viral, viral (B##ch!)")
			}
			else if (text == 6) {
				msg.channel.send("**Rap #6 - Together**\nYeah, I feel so sad\nAnd I feel so bad\nAnd I also feel\nFeel a little mad\n\nI don\’t know why\nI feel like my\nWhole life is a lie\nI just wanna die\nI don’t wanna live\nI just wanna stab myself with a knife\nI don’t need this s##t, I don\’t want this f##king life\n\nI\’m all alone\nOn my own\nIn a forest\nOvergrown\nThey left me here\nOut of fear\nScared that I would\nInterfere\nThey say I\’ll die\nAnd they lie\nAs they watch my\nLoved ones cry\nI don\’t know\nI\’m losing control\nI can\’t do this s##t\nAnymore\nI don\’t feel well\nI feel like h##l \nI just really\nNeed some help\n\nYeah, I need someone to help me\nI need energy\nAnd I\’ve been lonely\nCould use company\n\nI feel like I can\’t do this\nBut deep down I know I can\nSo come let\’s raise our hands\nLet\’s win this war and dance\nCome on, let\’s hold hands\nLet\’s do this for our friends\nWe can do this s##t\nWe can beat that b###h\n\nYeah, I need someone to help me\nI need energy\nAnd I\’ve been lonely\nCould use company\nBefore I couldn\’t do this\nNow I know I can\nCuz now I have my friends\nAnd they\’re holding my hands\n\nYeah, it\’s time to do this\nYeah, we can win this\nCome let\'s raise our hands\nLet\’s do it for our friends\nFriends and family\nLet\’s make sure we\'re free")
			}
			else if (text == 7) {
				msg.channel.send("**Rap #7 - Flex**\n\nFlex, flex, yeah I gotta go flex\nDominating like a t-rex \nKissed me, kissed me, girl what\’s next\nGirl don\’t worry, follow my footsteps\nFlex, flex, yeah I gotta go flex\nDominating like a t-rex \nKissed me, kissed me, girl what\’s next\nGirl don\’t worry, follow my footsteps\n\nYeah, I was poppin on the street\nI got ez\’s on my feet\nAnd I\’m rappin to the beat\nSometimes I look neat\nWhenever I come, I turn up the heat\nWhen I start to rap, I\’m on fire\nYou want a rap, it\’s me you gotta hire\nCome on, come on, we gotta go now\nWe gotta leave now, but I don\’t know how\nI don\’t know bout you, but I like to flex\nYeah I got deez gunz, so I flex, flex, flex\n(Yeah)\nFlex, flex, yeah I gotta go flex\nDominating like a t-rex \nKissed me, kissed me, girl what\’s next\nGirl don\’t worry, follow my footsteps\nFlex, flex, yeah I gotta go flex\nDominating like a t-rex \nKissed me, kissed me, girl what\’s next\nGirl don\’t worry, follow my footsteps\n\nChillz, Chillz, yeah I got them pills\nGotta rap about myself, I live on the hills\nI do many things, I got a lotta skills\nI be playing Call of Duty, I got 65 kills\n\nFlex, flex, yeah I gotta go flex\nDominating like a t-rex \nKissed me, kissed me, girl what\’s next\nGirl don\’t worry, follow my footsteps\nFlex, flex, yeah I gotta go flex\nDominating like a t-rex \nKissed me, kissed me, girl what\’s next\nGirl don\’t worry, follow my footsteps")
			}
			else if (text == 8) {
				msg.channel.send("**Rap #8 - Chillz**\n\nYeah, my name is Chillz\nAnd I got them pills\nAnd I live on the hills\nAnd I got a lot of skills\n\nYeah I'm Indian, yeah I'm Hindu\nI got a lot of gods that I pray to\nYo what you doing, what the heck is wrong with you\nWhat you tryin to do to my new Gucci shoes\nI just came down from the 14th floor\nGot in my Lambo\nStarted skrrting on the road\nAnd I go like woah-woah\nCome on, come on, to my house, you down?\nWhy you so sad, you got that frown\nYeah, my name is Chillz\nAnd I got them pills\nAnd I live on the hills\nAnd I got a lot of skills\nCome to my restaurant\nWe got free refills\nI'm also an actor\nI made a lot of films\nIn my mansion\nWe got no cheap thrills\nLook in my bank\nI got a lot of bills\n\nAyy, I'm also an athlete\nI play with my hands and play with my feet\nMy favorite sport is soccer tho\nCuz I can juke and score them goals\n\nYo, you just got destroyed\nIt was fair, it was square\nWhy you wanna fight when you know you're losing\nYo, you tryin to fight, that's amusing\n\nYeah, my name is Chillz\nAnd I got them pills\nAnd I live on the hills\nAnd I got a lot of skills\n\n(Yeah, It's Chillz on the beat\nWhenever he starts rappin he turns up the heat\nHe's too good, too hard to defeat\nYeah that's right, he's part of the elite)")
			}
			else {
				connection.query('select * from settings where servername = ?', [msg.guild.name], async function (error, results, fields) {
				const settingsembed = new Discord.MessageEmbed()
							.setColor('#0099ff')
							.setTitle(':warning: Error! :warning:')
							.addFields(
								{ name: 'Rap Not Found', value:`Please input a number from 1 to 8 for a rap!\nEx. \`${results[0].prefix}rap 1\``, inline: true },
								{ name: 'Tip!', value:`Do\`${results[0].prefix}raps\` for the list of raps!`, inline: true },
							);
				msg.channel.send(settingsembed);
				})
			}

	},
};